import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import type { LayoutProps } from "@/types/LayoutProps";
import Toast from "@/components/Toast/Toast";
import MotionLayout from "./MotionLayout";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: LayoutProps) {
  const { children } = props;

  return (
    <html lang="en">
      <body className={`${inter.className} font-['Inter'] antialiased h-full`}>
        <MotionLayout>
          <div className="container mx-auto w-full h-full flex min-h-screen text-zinc-800 p-6 font-sans">
            {children}
            <Toast />
          </div>
        </MotionLayout>
      </body>
    </html>
  );
}
